<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <PackageId>Leaf.ColorDetector</PackageId>
    <Version>1.1.1</Version>
    <Authors>Mitsuha9527</Authors>
    <Description>颜色检测库 — 基于 OpenCV + CIE ΔE2000 色差公式的工业视觉检测</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
	<Copyright>Copyright (c) 2024 Mitsuha9527</Copyright>
	<PackageTags>opencv;color detect</PackageTags>
	<RepositoryUrl>https://github.com/Mitsuha9527/Leaf.CvLibrary.git</RepositoryUrl>
	<PackageOutputPath>nupkg</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CvLibrary\CvLibrary.csproj" />
  </ItemGroup>

</Project>
